/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeObjectBuckets implements ObjectBucketInterface
type FakeObjectBuckets struct {
	Fake *FakeCephV1beta1
	ns   string
}

var objectbucketsResource = schema.GroupVersionResource{Group: "ceph.rook.io", Version: "v1beta1", Resource: "objectbuckets"}

var objectbucketsKind = schema.GroupVersionKind{Group: "ceph.rook.io", Version: "v1beta1", Kind: "ObjectBucket"}

// Get takes name of the objectBucket, and returns the corresponding objectBucket object, and an error if there is any.
func (c *FakeObjectBuckets) Get(name string, options v1.GetOptions) (result *v1beta1.ObjectBucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(objectbucketsResource, c.ns, name), &v1beta1.ObjectBucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ObjectBucket), err
}

// List takes label and field selectors, and returns the list of ObjectBuckets that match those selectors.
func (c *FakeObjectBuckets) List(opts v1.ListOptions) (result *v1beta1.ObjectBucketList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(objectbucketsResource, objectbucketsKind, c.ns, opts), &v1beta1.ObjectBucketList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ObjectBucketList{ListMeta: obj.(*v1beta1.ObjectBucketList).ListMeta}
	for _, item := range obj.(*v1beta1.ObjectBucketList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested objectBuckets.
func (c *FakeObjectBuckets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(objectbucketsResource, c.ns, opts))

}

// Create takes the representation of a objectBucket and creates it.  Returns the server's representation of the objectBucket, and an error, if there is any.
func (c *FakeObjectBuckets) Create(objectBucket *v1beta1.ObjectBucket) (result *v1beta1.ObjectBucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(objectbucketsResource, c.ns, objectBucket), &v1beta1.ObjectBucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ObjectBucket), err
}

// Update takes the representation of a objectBucket and updates it. Returns the server's representation of the objectBucket, and an error, if there is any.
func (c *FakeObjectBuckets) Update(objectBucket *v1beta1.ObjectBucket) (result *v1beta1.ObjectBucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(objectbucketsResource, c.ns, objectBucket), &v1beta1.ObjectBucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ObjectBucket), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeObjectBuckets) UpdateStatus(objectBucket *v1beta1.ObjectBucket) (*v1beta1.ObjectBucket, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(objectbucketsResource, "status", c.ns, objectBucket), &v1beta1.ObjectBucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ObjectBucket), err
}

// Delete takes name of the objectBucket and deletes it. Returns an error if one occurs.
func (c *FakeObjectBuckets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(objectbucketsResource, c.ns, name), &v1beta1.ObjectBucket{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeObjectBuckets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(objectbucketsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.ObjectBucketList{})
	return err
}

// Patch applies the patch and returns the patched objectBucket.
func (c *FakeObjectBuckets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ObjectBucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(objectbucketsResource, c.ns, name, data, subresources...), &v1beta1.ObjectBucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ObjectBucket), err
}
