/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1beta1"
	scheme "github.com/rook/rook/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CephObjectBucketsGetter has a method to return a CephObjectBucketInterface.
// A group's client should implement this interface.
type CephObjectBucketsGetter interface {
	CephObjectBuckets(namespace string) CephObjectBucketInterface
}

// CephObjectBucketInterface has methods to work with CephObjectBucket resources.
type CephObjectBucketInterface interface {
	Create(*v1beta1.CephObjectBucket) (*v1beta1.CephObjectBucket, error)
	Update(*v1beta1.CephObjectBucket) (*v1beta1.CephObjectBucket, error)
	UpdateStatus(*v1beta1.CephObjectBucket) (*v1beta1.CephObjectBucket, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.CephObjectBucket, error)
	List(opts v1.ListOptions) (*v1beta1.CephObjectBucketList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.CephObjectBucket, err error)
	CephObjectBucketExpansion
}

// cephObjectBuckets implements CephObjectBucketInterface
type cephObjectBuckets struct {
	client rest.Interface
	ns     string
}

// newCephObjectBuckets returns a CephObjectBuckets
func newCephObjectBuckets(c *CephV1beta1Client, namespace string) *cephObjectBuckets {
	return &cephObjectBuckets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cephObjectBucket, and returns the corresponding cephObjectBucket object, and an error if there is any.
func (c *cephObjectBuckets) Get(name string, options v1.GetOptions) (result *v1beta1.CephObjectBucket, err error) {
	result = &v1beta1.CephObjectBucket{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectbuckets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CephObjectBuckets that match those selectors.
func (c *cephObjectBuckets) List(opts v1.ListOptions) (result *v1beta1.CephObjectBucketList, err error) {
	result = &v1beta1.CephObjectBucketList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectbuckets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cephObjectBuckets.
func (c *cephObjectBuckets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cephobjectbuckets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cephObjectBucket and creates it.  Returns the server's representation of the cephObjectBucket, and an error, if there is any.
func (c *cephObjectBuckets) Create(cephObjectBucket *v1beta1.CephObjectBucket) (result *v1beta1.CephObjectBucket, err error) {
	result = &v1beta1.CephObjectBucket{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cephobjectbuckets").
		Body(cephObjectBucket).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cephObjectBucket and updates it. Returns the server's representation of the cephObjectBucket, and an error, if there is any.
func (c *cephObjectBuckets) Update(cephObjectBucket *v1beta1.CephObjectBucket) (result *v1beta1.CephObjectBucket, err error) {
	result = &v1beta1.CephObjectBucket{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cephobjectbuckets").
		Name(cephObjectBucket.Name).
		Body(cephObjectBucket).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cephObjectBuckets) UpdateStatus(cephObjectBucket *v1beta1.CephObjectBucket) (result *v1beta1.CephObjectBucket, err error) {
	result = &v1beta1.CephObjectBucket{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cephobjectbuckets").
		Name(cephObjectBucket.Name).
		SubResource("status").
		Body(cephObjectBucket).
		Do().
		Into(result)
	return
}

// Delete takes name of the cephObjectBucket and deletes it. Returns an error if one occurs.
func (c *cephObjectBuckets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cephobjectbuckets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cephObjectBuckets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cephobjectbuckets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cephObjectBucket.
func (c *cephObjectBuckets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.CephObjectBucket, err error) {
	result = &v1beta1.CephObjectBucket{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cephobjectbuckets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
