/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/rook/rook/pkg/apis/ceph.rook.io/v1beta1"
	scheme "github.com/rook/rook/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ObjectBucketsGetter has a method to return a ObjectBucketInterface.
// A group's client should implement this interface.
type ObjectBucketsGetter interface {
	ObjectBuckets(namespace string) ObjectBucketInterface
}

// ObjectBucketInterface has methods to work with ObjectBucket resources.
type ObjectBucketInterface interface {
	Create(*v1beta1.ObjectBucket) (*v1beta1.ObjectBucket, error)
	Update(*v1beta1.ObjectBucket) (*v1beta1.ObjectBucket, error)
	UpdateStatus(*v1beta1.ObjectBucket) (*v1beta1.ObjectBucket, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.ObjectBucket, error)
	List(opts v1.ListOptions) (*v1beta1.ObjectBucketList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ObjectBucket, err error)
	ObjectBucketExpansion
}

// objectBuckets implements ObjectBucketInterface
type objectBuckets struct {
	client rest.Interface
	ns     string
}

// newObjectBuckets returns a ObjectBuckets
func newObjectBuckets(c *CephV1beta1Client, namespace string) *objectBuckets {
	return &objectBuckets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the objectBucket, and returns the corresponding objectBucket object, and an error if there is any.
func (c *objectBuckets) Get(name string, options v1.GetOptions) (result *v1beta1.ObjectBucket, err error) {
	result = &v1beta1.ObjectBucket{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("objectbuckets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ObjectBuckets that match those selectors.
func (c *objectBuckets) List(opts v1.ListOptions) (result *v1beta1.ObjectBucketList, err error) {
	result = &v1beta1.ObjectBucketList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("objectbuckets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested objectBuckets.
func (c *objectBuckets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("objectbuckets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a objectBucket and creates it.  Returns the server's representation of the objectBucket, and an error, if there is any.
func (c *objectBuckets) Create(objectBucket *v1beta1.ObjectBucket) (result *v1beta1.ObjectBucket, err error) {
	result = &v1beta1.ObjectBucket{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("objectbuckets").
		Body(objectBucket).
		Do().
		Into(result)
	return
}

// Update takes the representation of a objectBucket and updates it. Returns the server's representation of the objectBucket, and an error, if there is any.
func (c *objectBuckets) Update(objectBucket *v1beta1.ObjectBucket) (result *v1beta1.ObjectBucket, err error) {
	result = &v1beta1.ObjectBucket{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("objectbuckets").
		Name(objectBucket.Name).
		Body(objectBucket).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *objectBuckets) UpdateStatus(objectBucket *v1beta1.ObjectBucket) (result *v1beta1.ObjectBucket, err error) {
	result = &v1beta1.ObjectBucket{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("objectbuckets").
		Name(objectBucket.Name).
		SubResource("status").
		Body(objectBucket).
		Do().
		Into(result)
	return
}

// Delete takes name of the objectBucket and deletes it. Returns an error if one occurs.
func (c *objectBuckets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("objectbuckets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *objectBuckets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("objectbuckets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched objectBucket.
func (c *objectBuckets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ObjectBucket, err error) {
	result = &v1beta1.ObjectBucket{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("objectbuckets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
